defaults:
  - base_trainer_config

name: 8_shot
configs:
  epochs: 0
  num_in_context_examples: 8
  cot_prompt: ""
  cot_reasons_filepath: null
  span_predictions: "icl_examples/biolinkbert_span_predictions.json"
  bertscore_filter: false
