defaults:
  - base_trainer_config

name: binary
configs:
  epochs: 0

  mode: binary # binary
  
  gradient_accumulation_steps: 0
  fusion_strategy: ""
  explicit_evidence: False
  common_lora_config: null
  section_lora_config: null
  common_polytropon_config: null

wandb_args:
  project_name: MediQA
  session_name: binary
  name: MediQA_binary 

