defaults:
  - base_trainer_config

name: cot_long_8_shot
configs:
  epochs: 0
  num_in_context_examples: 8
  cot_prompt: "Let's think step by step"
  cot_reasons_filepath: "icl_examples/cot_long_reasons.json"
  bertscore_filter: false
