defaults:
  - base_trainer_config

name: identify_one_error_sentence
configs:
  epochs: 0

  mode: identify_one_error_sentence # identify_one_error_sentence
  
  gradient_accumulation_steps: 0
  fusion_strategy: ""
  explicit_evidence: False
  common_lora_config: null
  section_lora_config: null
  common_polytropon_config: null

wandb_args:
  project_name: MediQA
  session_name: identify_one_error_sentence
  name: MediQA_identify_one_error_sentence 

