# @package _global_
defaults:
  - override /model: gpt3_api
  - override /data: mediqa
  - override /trainer: identify_n_error_sentences # not sure about this one 
  - override /prompt: prompt_identify_n_error_sentences
hydra:
  run:
    dir: outputs/gpt3_api/${now:%Y-%m-%d}/identify_n_error_sentences/${now:%H-%M-%S}