defaults:
  - base_instruction_config

instruction_template: "{icl_example}Consider this clinical text: {clinical_sentences}\nDoes it make sense? If not, which sentence that is incorrect and how would you fix it?\nAnswer: {cot_prompt}"
