defaults:
  - base_model_config

name: GPT-3.5-Turbo
configs:
  model_name_or_path: gpt-3.5-turbo
  model_type: api
  max_seq_len: 16384
  temperature: 0.0
  top_p: 1
  frequency_penalty: 0
  presence_penalty: 0
  max_tokens: 256
