defaults:
  - base_model_config

name: gpt3_api
configs:
  model_name_or_path: gpt3_api
  system_prompt: You are a clinician reviewing clinical texts that may or may not contain error. # Output your response in JSON format with a key named "replace_with" for what the <BLANK> should be replaced with. 
  # prompt_template: 
  # max_seq_len: 4096
  # system_prompt: You are a clinician who check if there is a contradiction or an entailment between a section of a clinical trial report and a statement.
  # temperature: 0.001
  # top_p: 0
  # top_k: 1
  # repetition_penalty: 1


  # "You are a helpful and knowledgeable assistant."
  # You will be provided with unstructured data, and your task is to parse it into CSV format.
  # Output your response in JSON format. In the JSON object, include keys 'error_flag' for error presence(0 if no error and 1 if there is an error), 'error_sentence_id' for erroneous sentence index, and 'corrected_sentence' for the corrected version of the sentence.\n\nClinical note:\n{clinical_sentences}"


  # Output your response in JSON format with a key named "replace_with" for what the <BLANK> should be replaced with. 
  # 