defaults:
  - base_model_config

name: GPT-4
configs:
  model_name_or_path: gpt-4-0125-preview
  model_type: api
  max_seq_len: 128000
  temperature: 0.0
  top_p: 1
  frequency_penalty: 0
  presence_penalty: 0
  max_tokens: 512
