defaults:
  - base_model_config

name: LLaMA2-70b-chat
configs:
  model_name_or_path: meta-llama/Llama-2-70b-chat-hf
  model_type: hf
  max_seq_len: 4096
  system_prompt: You are a clinician reviewing clinical texts that may or may not contain 1 incorrect sentence
  temperature: 0.001
  top_p: 0
  top_k: 1
  repetition_penalty: 1
