defaults:
  - base_model_config

name: Meditron-7b
configs:
  model_name_or_path: epfl-llm/meditron-7b
  model_type: hf
  max_seq_len: 2048
  temperature: 0.001
  top_p: 0
  top_k: 1
  repetition_penalty: 1
