defaults:
  - base_model_config

name: Mistral-7b-Instruct
configs:
  model_name_or_path: mistralai/Mistral-7B-Instruct-v0.1
  model_type: hf
  max_seq_len: 4096
  system_prompt: You are a clinician reviewing clinical texts that may or may not contain 1 incorrect sentence
  temperature: 0.001
  top_p: 0
  top_k: 1
  repetition_penalty: 1
