defaults:
  - base_model_config

name: Mistral-7B
configs:
  model_name_or_path: mistralai/Mistral-7B-v0.1
  model_type: hf
  max_seq_len: 4096
  temperature: 0.0
  top_p: 1
  frequency_penalty: 0
  presence_penalty: 0
  max_tokens: 512
