defaults:
  - base_config
  - data: mediqa
  - model: mistral_7b_instruct
  - trainer: 0_shot
  - prompt: prompt_none
  - experiment: null
  - _self_

# hydra:
#   output_subdir: null
random_seed: 1234

wandb_project: MEDIQA
wandb_entity: clee1997

debug: true

api_key_path: /Users/chaeeunlee/Documents/VSC_workspaces/mediqa/api_keys/openai_key.yaml