defaults:
  - base_config
  - data: mediqa
  - model: mistral_7b_instruct
  - trainer: 0_shot
  - prompt: prompt_none
  # - experiment: null
  - override: null
  - _self_

random_seed: 1234

debug: true

api_key_path: /Users/chaeeunlee/Documents/VSC_workspaces/mediqa/api_keys/openai_key.yaml